{% set name = "ncompare" %}
{% set version = "1.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ncompare-{{ version }}.tar.gz
  sha256: 629dea7f99ebc6763bbbc567de1d8b1889ce64c5ef93a21e543c29bb17dc10e9

build:
  entry_points:
    - ncompare = ncompare.console:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.9
    - numpy >=1.26.0
    - netcdf4 >=1.6.4
    - xarray >=2023.9
    - colorama >=0.4.6
    - openpyxl >=3.1.2

test:
  imports:
    - ncompare
  commands:
    - pip check
    - ncompare --help
  requires:
    - pip

about:
  home: https://github.com/nasa/ncompare
  summary: Compare the structure of two NetCDF files at the command line
  dev_url: https://github.com/nasa/ncompare
  doc_url: https://ncompare.readthedocs.io
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jhkennedy
    - danielfromearth
